import Head from 'next/head';
import Hero from '../components/Hero';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';

export default function Home() {
    return (
        <div>
            <Head>
                <title>PETAK Gov</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Hero heading='PETAKgov' message='Search, See, Support.' />
            <Slider slides={SliderData} />
        </div>
    );
}